apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: springboot-java-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: colanta06/java-app:v1.0.x
    argocd-image-updater.argoproj.io/java-app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
  finalizers:
  - "argoproj.io/argocd-resource-finalizer"  
spec:
  project: default
  source:
    repoURL: 'https://github.com/samueldison/springboot-java-app.git'
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true 
      - PrunePropagationPolicy=background 
      - PruneLast=true
      - ApplyOutOfSyncOnly=true